git:
  branch: master
slack:
  room: "eduid-builds"
script:
  - make dockers
upstream:
  - eduid-am
  - eduid-common
  - eduid-graphdb
  - eduid-lookup-mobile
  - eduid_msg
  - eduid-queue
  - eduid-scimapi
  - eduid-userdb
  - eduid-webapp
clean_workspace: false
